[2018-07-2701:48:19 PM-test.py-DEBUG:dsf]
[2018-07-2702:27:25 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:27:26 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:27:26 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:27:26 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:27:26 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:27:26 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:27:26 PM-HttpClient.py-ERROR:download  exceed max_try]
[2018-07-2702:27:32 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:27:32 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:27:32 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:27:32 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:27:32 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:27:33 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:27:33 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:27:33 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:27:33 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:27:33 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:27:33 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:27:33 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:27:33 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:27:33 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:27:33 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:27:33 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:27:33 PM-HttpClient.py-ERROR:download  exceed max_try]
[2018-07-2702:27:50 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:27:50 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:27:50 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:29:14 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:29:14 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 200 None]
[2018-07-2702:29:24 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:29:24 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 200 None]
[2018-07-2702:29:56 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:29:56 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:29:56 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:29:56 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:29:56 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:29:57 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:29:57 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:29:57 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:29:57 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:29:57 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:29:57 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:29:57 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:29:57 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:29:57 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 302 0]
[2018-07-2702:29:57 PM-connectionpool.py-DEBUG:Starting new HTTPS connection (1): www.baidu.com:443]
[2018-07-2702:29:57 PM-HttpClient.py-ERROR:download exception: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /error.html (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) ]
[2018-07-2702:29:57 PM-HttpClient.py-ERROR:download  exceed max_try]
[2018-07-2702:30:41 PM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.baidu.com:80]
[2018-07-2702:30:41 PM-connectionpool.py-DEBUG:http://www.baidu.com:80 "GET / HTTP/1.1" 200 None]
[2018-07-3109:07:04 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): c.m.163.com:80]
[2018-07-3109:07:04 AM-connectionpool.py-DEBUG:http://c.m.163.com:80 "GET /nc/article/preload/DN5D8FQU051184MS/full.html HTTP/1.1" 403 None]
[2018-07-3109:08:30 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): c.m.163.com:80]
[2018-07-3109:08:30 AM-connectionpool.py-DEBUG:http://c.m.163.com:80 "GET /nc/article/preload/DN5D8FQU051184MS/full.html HTTP/1.1" 403 None]
[2018-07-3109:09:03 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.c.m.163.com:80]
[2018-07-3109:09:03 AM-HttpClient.py-ERROR:download exception: HTTPConnectionPool(host='www.c.m.163.com', port=80): Max retries exceeded with url: /nc/article/preload/DN5D8FQU051184MS/full.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000032CAB70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) ]
[2018-07-3109:09:03 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.c.m.163.com:80]
[2018-07-3109:09:03 AM-HttpClient.py-ERROR:download exception: HTTPConnectionPool(host='www.c.m.163.com', port=80): Max retries exceeded with url: /nc/article/preload/DN5D8FQU051184MS/full.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003322160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) ]
[2018-07-3109:09:03 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.c.m.163.com:80]
[2018-07-3109:09:03 AM-HttpClient.py-ERROR:download exception: HTTPConnectionPool(host='www.c.m.163.com', port=80): Max retries exceeded with url: /nc/article/preload/DN5D8FQU051184MS/full.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003322080>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) ]
[2018-07-3109:09:03 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): www.c.m.163.com:80]
[2018-07-3109:09:03 AM-HttpClient.py-ERROR:download exception: HTTPConnectionPool(host='www.c.m.163.com', port=80): Max retries exceeded with url: /nc/article/preload/DN5D8FQU051184MS/full.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000033220F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) ]
[2018-07-3109:09:03 AM-HttpClient.py-ERROR:download  exceed max_try]
[2018-07-3109:11:11 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:11:11 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:11:11 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:11:11 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:11:11 AM-HttpClient.py-ERROR:download  exceed max_try]
[2018-07-3109:12:03 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:12:48 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:12:48 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:12:48 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:12:48 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:12:48 AM-HttpClient.py-ERROR:download  exceed max_try]
[2018-07-3109:13:16 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:13:16 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:13:16 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:13:16 AM-HttpClient.py-ERROR:download exception: request() got an unexpected keyword argument 'header' ]
[2018-07-3109:13:16 AM-HttpClient.py-ERROR:download  exceed max_try]
[2018-07-3109:14:26 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:14:26 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://c.m.163.com/nc/article/preload/DN5D8FQU051184MS/full.html HTTP/1.1" 403 None]
[2018-07-3109:15:47 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:15:47 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://c.m.163.com/nc/article/preload/DN5D8FQU051184MS/full.html?Connection=keep-alive&Accept-Encoding=gzip&User-Agent=Mozilla%2F5.0+%28Linux%3B+Android+7.1.1%3B+MI+MAX+2+Build%2FNMF26F%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F64.0.3282.137+Mobile+Safari%2F537.36+JsSdk%2F2+NewsArticle%2F6.8.1+NetType%2Fwifi HTTP/1.1" 403 None]
[2018-07-3109:16:47 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:16:47 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://www.baidu.com/?Connection=keep-alive&Accept-Encoding=gzip&User-Agent=Mozilla%2F5.0+%28Linux%3B+Android+7.1.1%3B+MI+MAX+2+Build%2FNMF26F%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F64.0.3282.137+Mobile+Safari%2F537.36+JsSdk%2F2+NewsArticle%2F6.8.1+NetType%2Fwifi HTTP/1.1" 200 None]
[2018-07-3109:16:58 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:16:58 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://www.baidu.com/?Connection=keep-alive&Accept-Encoding=gzip&User-Agent=Mozilla%2F5.0+%28Linux%3B+Android+7.1.1%3B+MI+MAX+2+Build%2FNMF26F%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F64.0.3282.137+Mobile+Safari%2F537.36+JsSdk%2F2+NewsArticle%2F6.8.1+NetType%2Fwifi HTTP/1.1" 200 None]
[2018-07-3109:19:12 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:19:12 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://c.m.163.com/nc/article/preload/DN5D8FQU051184MS/full.html?Connection=Keep-Alive&Host=c.m.163.com&Accept-Encoding=gzip&User-Agent=NewsApp%2F39.1+Android%2F8.1.0+%28xiaomi%2FRedmi+Note+5%29 HTTP/1.1" 403 None]
[2018-07-3109:20:37 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:20:37 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://c.m.163.com/nc/article/preload/DNAUB95305119GS3/full.html?Connection=Keep-Alive&Host=c.m.163.com&Accept-Encoding=gzip&User-Agent=NewsApp%2F39.1+Android%2F8.1.0+%28xiaomi%2FRedmi+Note+5%29 HTTP/1.1" 403 None]
[2018-07-3109:21:16 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:21:16 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://c.m.163.com/nc/article/preload/DNAUB95305119GS3/full.html?Connection=Keep-Alive&Host=c.m.163.com&Accept-Encoding=gzip&User-Agent=NewsApp%2F39.1+Android%2F8.1.0+%28xiaomi%2FRedmi+Note+5%29 HTTP/1.1" 403 None]
[2018-07-3109:22:33 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:22:33 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://c.m.163.com/nc/article/preload/DNAUB95305119GS3/full.html HTTP/1.1" 200 None]
[2018-07-3109:30:41 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:30:42 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://c.m.163.com/nc/article/preload/DN5D8FQU051184MS/full.html HTTP/1.1" 200 None]
[2018-07-3109:42:21 AM-connectionpool.py-DEBUG:Starting new HTTP connection (1): 127.0.0.1:8888]
[2018-07-3109:42:21 AM-connectionpool.py-DEBUG:http://127.0.0.1:8888 "GET http://c.m.163.com/nc/article/preload/DN5D8FQU051184MS/full.html HTTP/1.1" 200 None]
